# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Welcome to our workshop "Using R for reproducible scientific research" 
subtitle: The goal of this workshop is to teach beginner programmers how to write 
  modular code and adopt best practices in using R for data analysis. 
If you have any questions, please contact us at:
email: mexicansatucdavis@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The codes and lessons covered in this course were provided by Dr. Rayna 
  Harris (UCD Data Lab), and we appreciate her collaboration with the Mexican Graduate Student 
  Association at UC Davis. 
  We believe that this workshop will be useful for providing attendes with a solid grounding
  in R fundamentals and teach scientific computing best practices such as breaking down analysis
  into modules, automating tasks, and encapsulation. 
  Please note that this workshop focuses on the fundamentals of R programming and not on 
  statistical analysis. 
  Thanks for participating!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mexicans_at_ucdavis
github_username:  s-dgordon

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
